/**
 * Generates the Builder agent's deployable source: a JS module that
 * default-exports `new Agent("builder-{idea}", {...})` from "oncell".
 *
 * All prose (identity, skill, run briefing) is computed here at generation
 * time and embedded as JSON string literals, so the generated JS stays tiny
 * and mechanical: resolve the cell id (task args, falling back to agent
 * memory for self-scheduled wakes), pick a run token, substitute the
 * briefing placeholders, and run ONE agent.llm loop — the manifest
 * capabilities (cells, schedule) are that loop's tools.
 */

import {
  autoRunPreamble,
  BRIEFING_AUTO_PREAMBLE,
  BRIEFING_CELL_ID,
  BRIEFING_KIND,
  BRIEFING_RUN,
  BRIEFING_SNAPSHOT_KEY,
  BUILDER_BUDGET_PER_DAY_CENTS,
  builderAgentName,
  builderIdentityInstructions,
  IMPROVE_SKILL_DESCRIPTION,
  IMPROVE_SKILL_NAME,
  improveSkillInstructions,
  runBriefingTemplate
} from './agent-def'
import { DEFAULT_BUILDER_MODEL } from '../builder/contract'

/** Ceiling on think→act steps for one build/improve pass. */
export const MAX_STEPS_PER_PASS = 80
/** Ceiling on spend (dollars) for one build/improve pass. */
export const MAX_COST_PER_PASS = 2

/** The deployable Builder source for an idea. */
export function builderAgentSource(ideaName: string, ideaText: string): string {
  const agentName = builderAgentName(ideaName)
  return `/** kaka Builder agent for idea ${JSON.stringify(ideaName)} — generated by kaka, do not edit. */
import { Agent, tools, skill } from "oncell";

const IDENTITY_INSTRUCTIONS = ${JSON.stringify(builderIdentityInstructions(ideaName, ideaText))};
const IMPROVE_SKILL = {
  name: ${JSON.stringify(IMPROVE_SKILL_NAME)},
  description: ${JSON.stringify(IMPROVE_SKILL_DESCRIPTION)},
  instructions: ${JSON.stringify(improveSkillInstructions())},
};
const BRIEFING_TEMPLATE = ${JSON.stringify(runBriefingTemplate())};
const AUTO_PREAMBLE = ${JSON.stringify(autoRunPreamble())};

const CELL_ID_MEMORY_KEY = "kaka:cell_id";
const MAX_STEPS_PER_PASS = ${MAX_STEPS_PER_PASS};
const MAX_COST_PER_PASS = ${MAX_COST_PER_PASS};

const agent = new Agent(${JSON.stringify(agentName)}, {
  identity: {
    instructions: IDENTITY_INSTRUCTIONS,
    model: ${JSON.stringify(DEFAULT_BUILDER_MODEL)},
    budgets: { perDayCents: ${BUILDER_BUDGET_PER_DAY_CENTS} },
  },
  capabilities: [tools.memory, tools.cells, tools.schedule],
  skills: [
    skill(IMPROVE_SKILL.name, {
      description: IMPROVE_SKILL.description,
      instructions: IMPROVE_SKILL.instructions,
      tools: [tools.cells, tools.schedule],
    }),
  ],
});

function fill(template, values) {
  let text = template;
  for (const [placeholder, value] of Object.entries(values)) {
    text = text.split(placeholder).join(value);
  }
  return text;
}

async function resolveCellId(args) {
  const passed = typeof args.cell_id === "string" && args.cell_id.length > 0 ? args.cell_id : undefined;
  if (passed !== undefined) {
    // Remember it: self-scheduled wakes re-invoke with only { prompt }.
    await agent.memory.set(CELL_ID_MEMORY_KEY, passed);
    return passed;
  }
  const remembered = await agent.memory.get(CELL_ID_MEMORY_KEY);
  if (typeof remembered === "string" && remembered.length > 0) {
    return remembered;
  }
  throw new Error("no cell_id available: pass cell_id in the task args at least once");
}

async function runPass(kind, args) {
  const cellId = await resolveCellId(args);
  // A missing run token means the platform woke us (schedule), not kaka.
  const isSelfScheduled = typeof args.run !== "string" || args.run.length === 0;
  const run = isSelfScheduled ? "auto-" + Date.now().toString(36) : args.run;
  const snapshotKey = typeof args.snapshot_key === "string" ? args.snapshot_key : "";
  const briefing = fill(BRIEFING_TEMPLATE, {
    "${BRIEFING_KIND}": kind,
    "${BRIEFING_CELL_ID}": cellId,
    "${BRIEFING_RUN}": run,
    "${BRIEFING_SNAPSHOT_KEY}": snapshotKey,
    "${BRIEFING_AUTO_PREAMBLE}": isSelfScheduled ? AUTO_PREAMBLE : "",
  });
  const result = await agent.llm(briefing, {
    maxSteps: MAX_STEPS_PER_PASS,
    maxCost: MAX_COST_PER_PASS,
  });
  return { run, kind, status: result.status, summary: result.text };
}

agent.task("build", (args) => runPass("build", args));
agent.task("improve", (args) => runPass("improve", args));

export default agent;
`
}
